### PR TITLE
[#14] Calling default_category on NotificationRenderer.configuration

### LINKED ISSUE #14: Calling default_category on NotificationRenderer.configuration
`undefined method `default_category' for #<NotificationRenderer::Configuration:0x00007fdac6ed3930>`

Occurs when attempting to use the render_notifications method. Seems to just be a case of an incorrect method call. `default_category` is a method for `NotificationSettings.configuration` but not for `NotificationRenderer.configuration`.

### PR DESCRIPTION
**Pull request by DannySantos**
Resolves #14

### CODE REVIEW

**Comment by DannySantos** [comment]
No worries mate. Great work on the gem, I love it!

**Comment by keshavbiswa** [comment]
Having the same problem again

when I run this 

```ruby Notification.create(target: User.find_by_email(self.user_mail), object: self, type: 'claim_share')
```

I get

undefined method `default_category' for #<NotificationRenderer::Configuration:0x000000000639a250> Did you mean? default_type

**Comment by jonhue** [comment]
@keshavbiswa Do you fetch this gem from the master branch, or from Rubygems?

**Comment by jonhue** [comment]
Discussion continued in #29

**Comment by jonhue** [comment]
I just pushed version 1.2.6 to rubygems.org.

**Pull request merged**
